name: Run python3

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: list files
      run: |
        ls
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Run Python Script
      run: |
        python3 positive_earnings.py
    
